### ISSUE TITLE
pinidea 0.2 运营计划以及跟踪

### ISSUE THREAD

**Issue by ben7th** [mindpin/TouchIdea#30]
pinidea 0.2 开发完毕后，要开展运营工作。我们制定一个计划来说明要做的事情，哪些人来做，期望得到什么效果，要怎么验收，等等。

我先列出一个提纲，大家通过讨论的形式来补充
需求组先沟通，开发组再补充

---

**在运营工作开始之前，必须完成程序集成以及团队内部测试。
在这个阶段虽然程序可能已经完成度较高，也可用，但由于很多必要的准备工作未做
不建议贸然推出去让别人知道。运营工作不是简单告诉别人“做好了”你来试试吧，这么简单。必须考虑很多因素，要认真的做。**
1. **产品发布**
   （程序逻辑完毕并内部测试后，发布前还要进行的一些必要准备。如帮助文档，DEMO，关于页面，宣传资料等）
2. **重点场景和预置数据**
   （希望用户重点体验以收集用户反馈的场景，以及为了这些场景能够玩得顺畅所准备的预置数据）
3. **推广渠道和策略**
   （每种渠道如何发放，如何统计转化率）
4. **数据统计方法和目标**
   （包括接下来数周数月每一阶段，各个场景期望达到的统计数据指标，以及未达到时如何调整的预先计划）
5. **搜索引擎优化**
   （围绕SEO要做的一些必要调整）
6. **社区账号准备**
   （用来配合进行运营工作的新浪微博，微信公众号等）
7. **反馈渠道和反馈管理**
   （产品内表单提交，微博反馈，产品主页反馈）
8. **产品内每日互动**
   （由我们自己的工作人员参与的产品内互动，如何进行，如何验收）

**Comment by ben7th** [comment]
## 第一次讨论 2015-4-13 14:00 - 15:00
1. 产品发布
   要细化的点包括：intro 页面，帮助页面，关于页面。几种不同尺寸的宣传图片，以及以“介绍功能”为名义的宣传图片；
   以及 DEMO。DEMO 不是给用户看的，是给将来的合作方看的。
2. 重点场景指，当前运营计划围绕的关键中心场景（而不是产品的所有场景。）
   预置数据指为了让外面来的用户和我们自己的互动工作人员便于使用场景而置入的数据
3. 渠道指微博，微信，email，论坛等渠道。策略指发什么，何时发。
4. 数据统计是针对推广策略来一一对应的，包括每个时间阶段预期要达到的数据（可以有多个不同的指标）以及最后高于和低于指标时的处理方法
5. 工作包括每页的 title，meta，以及搜索引擎对于网站结构的抓取是否合理。以及对 robots.txt 的微调。
6. 这个指每个推广渠道，需要用到的账号，预先准备出来，而不是到时再去准备。
7. 预先把所有可能的反馈渠道考虑好，并制作成表格，便于汇总；
   以及在各个反馈渠道给用户的标准回复。
8. 指我们的工作人员每天要在产品内做的操作。

---

计划制定方法：
- 针对以上八项，尽可能地去想：
  1. 需要做的准备材料（包括图片，文案，网页，表格，文档模板）
  2. 需要在计划执行阶段执行的工作（分为一次执行和周期执行）
- 把八项的材料准备好，相关工作项汇总到一起之后，根据每项工作的工作量，重要程度等安排执行的先后顺序。做出接下来 1-2 个月内的具体执行顺序
- 在这之后，并且在程序集成完毕并完成内部测试之后，开始按照执行顺序执行

**Comment by ben7th** [comment]
1. 产品发布
    要细化的点包括：intro 页面，帮助页面，关于页面。几种不同尺寸的宣传图片，以及以“介绍功能”为名义的宣传图片；
    以及 DEMO。DEMO 不是给用户看的，是给将来的合作方看的。

2. 重点场景指，当前运营计划围绕的关键中心场景（而不是产品的所有场景。）
    预置数据指为了让外面来的用户和我们自己的互动工作人员便于使用场景而置入的数据

3. 渠道指微博，微信，email，论坛等渠道。策略指发什么，何时发。

4. 数据统计是针对推广策略来一一对应的，包括每个时间阶段预期要达到的数据（可以有多个不同的指标）以及最后高于和低于指标时的处理方法

5.

**Comment by ben7th** [comment]
## 2015-4-15 上午

### 产品发布

一般情况下：用户会按照以下顺序接触到这些内容：
1. 通过各种推广方式看到宣传图
2. 通过宣传图二维码或附带链接来到产品网站，看到DEMO
3. 注册后看到 INTRO
4. 使用过程中会去看帮助和关于

#### intro

形式：三页手机屏幕大小的静态网页，以逐页展现的形式呈现
参考：吴笛给出一些
提交物：三张静态网页（满足不同手机屏幕的分辨率，主要信息要能在不同手机显示。）
负责人：宋亮根据参考来制作
备注：由于目前应用是网页应用，因此 intro 的出现时机和一般 app 有所差别。先准备好提交物，最后再确定出现时机。

---

#### 帮助页面

形式：以FAQ的形式提供，以文本列出典型的产品试用问题和回答清单；
参考：
- 豆瓣：
  ![](http://img.teamkn.com/i/MIv2naur.png@200w)
- 豆瓣东西：
  ![](http://img.teamkn.com/i/r6GHC44C.png@200w)
- 豆瓣东西：
  ![](http://img.teamkn.com/i/uNhoM3lm.png@200w)

提交物：
- 吴笛以 markdown 文档提交。宋亮整理成静态网页。

负责人：吴笛根据参考来制作
备注：无

---

#### 关于页面

形式：
- 一个网页，包含的要素有：LOGO，产品名，一句话简介，域名，版权信息（包括用到的开源软件信息）
- 还有一个网页是开发者名单和致谢（以后不断添加）（在关于页里有个链接点过去）

参考：
![](http://img.teamkn.com/i/X8zTFLNm.png@200w)

提交物：网页
负责人：宋亮
备注：无

---

#### 宣传图

形式：两种尺寸的宣传图
- 用于手机屏幕显示的：比例是 9:16， 最高分辨率 720 x 1280
- 用于PC和平板屏幕显示的：比例是 16:10 最高分辨率 1680 x 1050 
- 图片上要列出主要的功能，以及二维条码

参考：
- ![](http://img.teamkn.com/i/o5Ctr9QM.png@200h)
- ![](http://img.teamkn.com/i/iPD3ITMm.png@200h)

提交物：图片
负责人：宋亮

---

### DEMO

形式：滚动的活动网页，针对手机屏幕
参考：http://tnc.org.cn/#Home
提交物：静态网页
负责人：宋亮

**Comment by pimgeek** [comment]
# 2015-4-15

## 重点场景1

### 场景描述

本轮迭代希望用户重点体验场景是：在一个互联网上的工具软件爱好者群体中，某位用户提出一个自己非常习惯于使用的软件工具，并且列出它的亮点，他把工具简介和亮点列表分享给大家，并收集他们的意见和吐槽。

### 操作方法

在场景 1 中的操作方法如下：

议题发起者打开 pinidea；创建一个普通议题，输入描述文字和相关的预置选项，然后发布议题并邀请其他关注这类产品的人参与议题。

议题参与者通过议题的永久链接，进入 pinidea 并打开议题，查看议题说明和相关的预置选项，然后进行投票操作，补充最多一个新选项，并提交。

### 可以照顾用户的地方

**作为议题发起者**

A 创建普通议题时，议题描述中给出更贴近重点场景的占位文字。
B 创建普通议题的，从预置选项输入界面返回议题描述输入界面的【上一步】按钮看上去更加可操作的。

### 预置数据

---

暂时不适合当前讨论点的内容：

1 希望发布之前能够预览已经写好的全部内容
2 首页的主题之间是否要像【我参与的议题页面】那样，留出分隔线
3 发布失败时保持主题的草稿

**Comment by ben7th** [comment]
### 2015-4-16

#### 搜索引擎优化

目前本应用不支持公开访问。以下讨论基于假设它能够公开访问时，给每个页面添加的 meta 信息

**每个页面要添加的 meta 信息及其含义**

```
<meta name='description' content='网站简介'>
<meta name='keywords' content='网站,关键字'>
```

以上两个是最基本的描述和关键字信息。
另外，需要根据 http://open.weibo.com/widget/like.php 的要求，为每个页面确定 Open Graph 信息
根据吴笛的调研，QQ 和微信也会读取网页上的 Open Graph 信息来生成他们产品中的 infocard

所以，我们只要在 meta 信息中添加必要的 Open Graph 信息，以及 description keywords 信息就好

以下根据页面流图来逐页指定
http://img.teamkn.com/i/iAl0pb3H.png

---

**通用（如果没有特别说明，则页面默认用这个）**

title: pinIdea
description: pinIdea 是一个以社交投票的形式来收集意见信息的网络应用。使用者可以借助这个应用来快速贡献自己的想法和了解别人的想法，并且以生动的形式查看议题投票结果。
keywords: pinIdea,mindpin,投票,议题,意见,意见收集,点子,点子收集,拼点子,点赞,调查,集思广益,单选,多选,点评,分享,商品,导购
og:description: 同 description
og:type: app (特定页面会用别的类型)
og:image: 应用 LOGO（包括 http://）（所有页都用本站LOGO，不去特别处理了）
og:title 同页面 title
og:url 当前页面 url（包括 http://）

示例 html

``` html
<!DOCTYPE html>
<html lang='zh'>
  <head>
    <title>pinidea</title>

    <meta name='description' content='pinIdea 是一个以社交投票的形式来收集意见信息的网络应用。使用者可以借助这个应用来快速贡献自己的想法和了解别人的想法，并且以生动的形式查看议题投票结果。'>
    <meta name='keywords' content='pinIdea,mindpin,投票,议题,意见,意见收集,点子,点子收集,拼点子,点赞,调查,集思广益,单选,多选,点评,分享,商品,导购'>

    <meta property='og:type' content='app'>
    <meta property='og:url' content='当前网页地址'>
    <meta property='og:title' content='pinIdea'>
    <meta property='og:description' content='pinIdea 是一个以社交投票的形式来收集意见信息的网络应用。使用者可以借助这个应用来快速贡献自己的想法和了解别人的想法，并且以生动的形式查看议题投票结果。'>
    <meta property='og:image' content='网站LOGO'>
```

$1:
title: pinidea - 登录

$2:
title: pinIdea - 议题广场

$3:
title: pinIdea - #{议题内容}
description, og:description: 所有选项的文字，用竖线分隔

$4: 
title: pinIdea - 投票完毕

$7:
title: pinIdea - 搜索

$11 - $12,
title: pinIdea - 创建议题 - 普通

$14 - $17
title: pinIdea - 创建议题 - 分享

$28 - $29
title: pinIdea - 创建议题 - 点评

$26
title: pinidea - 题材分类

$27
title: pindea - 题材分类 - #{子分类名}

$13
title: pinidea - 创建成功

$18
title: pinIdea - 通知

$19
title: pinIdea - 用户

$20
title: pinIdea - 用户信息

$21
title: pinIdea - 我参与的议题

$22
title: pinIdea - 我发起的议题

$23
title: pinIdea - 设置

$24
title: pinIdea - 意见反馈

$25
title: pinIdea - 关于

---

此版本不设置 robots.txt
需要设置时参考 
http://help.baidu.com/question?prod_en=search&class=%BD%FB%D6%B9%CB%D1%CB%F7%D2%FD%C7%E6%CA%D5%C2%BC%B5%C4%B7%BD%B7%A8

**Comment by ben7th** [comment]
### 2015-4-16

#### 7. 反馈渠道汇总

**由吴笛设计一个网页表格，来汇总所有渠道的反馈信息。
网页表格需要记录每条反馈的来源，时间，处理意见，处理结果等。**
1. www.mindpin.com
   反馈提交方法：点击打开 pinIdea 的产品评论页（目前没有，要加上），在产品评论页添加评论
   反馈回应方法：在评论中回复”建议已收到，感谢您的关注，您的持续使用能帮助我们更好的改进产品。“
   反馈记录方法：把用户发的评论汇总到汇总表，记录时间，来源标记为 mindpin
2. 新浪微博
   反馈提交形式：
   -  微博私信
   -  微博评论（可能会评论在我们的微博账号下面，即使那条微博和产品无关）
   -  微博@我们的账号
   -  在微博中提到我们的产品名
   
   反馈回应方法：
   - 针对私信，回私信，标准回复
   - 针对评论，回评论，标准回复
   - 针对@我们的，评论他的那条微博，并同时转发
   - 经常搜索此类微博，找到的话，如果值得回应，则评论他的微博并转发·
   
   反馈记录方法：把以上信息记录到汇总表，来源标记为新浪微博。由于我们团队准备的多个微博账号都可能收到反馈，所以每天应该就多个账号来记录。并标记是从哪个账号来的。
3. 产品内的意见反馈（对应页面流图的 $24）
   反馈提交形式：应用内功能
   反馈回应方法：无需回应
   反馈记录方法：从网站后台获得所有反馈，记录来源为 pinidea，记录时间，汇入总表
4. 微信（待定，需要先讨论议题3）

**Comment by ben7th** [comment]
### 2015-4-17

#### 2. 重点场景和预置数据

**场景：商品分享**

议题发起者点击创建议题，选择”分享“类型，输入一个商品页面网址，生成 infocard 之后，撰写议题描述和添加一些选项。
议题参与者根据自己对这个商品的判断和意见，对选项进行投票，同时也允许补充一个自己的选项。

目前支持的商品页面网址清单以及解析测试页地址：
http://urlinfo.4ye.me/

数据准备：
预置若干个包含商品信息的议题，让来到这里的用户可以比较容易地看到和参与这些议题。并且受到启发，自己发类似的议题来让人参与。

需要决策的内容：
1. 准备多少数据？
2. infocard 来自哪些网站？
3. 有哪些商品类型，各占多少比例？
4. 有哪些预置选项，不同的商品分别添加什么预置选项？

**场景：软件，网站和娱乐产品点评**

议题发起者点击创建议题，选择”点评“类型，选择题材类型，再从选择的类型中选择一个题材，作为议题要引用的 infocard. 撰写议题描述并添加一些选项。
议题参与者根据自己对这个特定题材的判断和意见，对选项进行投票，同时也允许补充一个自己的选项。

数据准备：
预置若干个包含网站，应用软件，娱乐产品信息的题材，作为系统内预置的 infocard 数据。让用户在进行”点评“类型议题创建时，可以从较多的题材中选择。

并且，预置若干个包含以上部分题材信息（不是全部）的议题，让来到这里的用户可以比较容易的看到和参与这些议题，并且受到其他，自己发类似的议题来让人参与。

需要决策内容：
1. 准备多少数据
2. 有哪些类型？（对应”创建点评议题“中的题材选择界面, http://img.teamkn.com/i/iAl0pb3H.png, $26）
3. 不同的类型各占多少比例？
4. 从中选取哪些题材来预置议题？
5. 预置议题包含哪些选项？

---

需要预置的三类数据
1. 1500个左右的infocard，关于工具软件，教育软件，娱乐软件和游戏
   用途：
   - 供我们创建一部分预置议题时引用
   - 供新增用户创建“点评”类型议题时引用
2. 500个“点评”类型的预置议题，以及选项。这些预置议题引用的数据就是上述infocard中的500个
   用途：
   - 供新增用户参与和模仿
   - 供团队运营人员完成后续日常工作
3. 500个“分享”类型的预置议题，以及选项。这些预置议题通过引用由商品url解析而来的数据生成（仅限于目前支持的网站范围）
   用途：
   - 供新增用户参与和模仿
   - 供团队运营人员完成后续日常工作

---

**关于场景 1 的决策问题回复：**
1. 准备多少数据？
   500个“分享”类型的预置议题，以及选项。
2. infocard 来自哪些网站？
   淘宝，天猫，京东，亚马逊，当当，一号店，无印良品，国美，宜家，易迅
3. 有哪些商品类型，各占多少比例？
4. 有哪些预置选项，不同的商品分别添加什么预置选项？
   每个网站50个
   50个尽量选择不同类型的商品
   最终要求收集500个，需求组先准备30个当例子，每人找10个
   选项3-5个，要求选项需要比较紧扣产品

**关于场景 2 的决策问题回复：**
1. 准备多少数据？
   1500个 infocard，用其中500个作为预置议题题材
2. 有哪些类型？（对应”创建点评议题“中的题材选择界面, http://img.teamkn.com/i/iAl0pb3H.png, $26）
   五个大类：
   工具，教育，社区，休闲，游戏
   以上五个大类基本是互斥的，不会有交集
3. 不同的类型各占多少比例？
   每个大类找 300 个软件
4. 从中选取哪些题材来预置议题？
   从中选取 500 个题材作为预置议题。
   各类 100 个。
5. 预置议题包含哪些选项？
   3-5 个选项。
   每个人找 x 个题材，从中指定 x/3 个作为预置议题，并附上选项提交

需求组先准备30个题材 + 预置议题选项作为例子

**关于普通议题**

准备 500 个。
内容五花八门，但都没有 infocard，都是纯文字描述 + 选项。
可以是送礼选择，甜咸豆腐脑，你最喜欢的品牌等。
原则上要避免主观视角的议题，这样运营比较好跟踪
选项数比较灵活

需求组先准备30个议题+选项作为例子

**Comment by ben7th** [comment]
### 2015-4-21

#### 场景：商品分享的预置数据样本汇总讨论结果记录

准备过程中遇到以下问题
- 需求组在准备数据样本的过程中普遍感觉到选项不好想，即使想出来也比较单一
- 有些用户可能仅仅是发出商品信息想让大家吐槽，自己并没有什么预置想法，要求预置选项有些强人所难
- 对于商品的讨论氛围应该是比较随意的，如果一定要强制写议题描述，可能会让大家感觉被限制住了

由于这些因素，因此目前觉得应该对商品类型的议题创建进行以下调整：
- 粘贴网址生成 infocard 后，议题描述作为可选项，允许不写。文字输入框里有预置文字“这是一件来自#{商品网站}的购物分享，给出你的看法吧”。创建者可以自行修改议题描述。
- 预置选项不再强制要求两项。但是会有固定的不可修改的三项“好（大拇指向上图标）”，“（差）大拇指向下图标”，“没想法”。如果议题创建者不再补充任何选项，那么议题发出去就是这三个选项；如果议题创建者补充了 N 个选项，发出去就是 N + 3 个选项。同时议题参与者仍然可以补充更多选项。

这样调整后，准备 500 个商品分享的议题就变成了单纯的准备 500 个商品网址，而不带有预置选项（除了默认的三个选项）。不过出于研究用户行为的目的，其中仍要准备一部分带有预置选项的商品信息。

数据准备方案变为：
1. 准备 500 个来自不同网站的商品信息。
2. 针对其中 100 想设想议题和选项。

数据提交格式：

``` yaml
# 第一条数据（只有商品网址，没有预置议题选项，这种数据共需要400条）
- url: http://detail.tmall.com/item.htm?spm=a230r.1.14.28.wo35GN&id=18699534618&ns=1&abbucket=3

# 第二条数据（有商品网址，有预置议题和选项，这种数据共需要100条）
- url: http://detail.tmall.com/item.htm?id=39151345462
  desc: 对于这种概念手表大家有什么看法？
  options:
    - 好看
    - 不好看
    - 智商不够看不懂
    - 太贵！求淘宝同款
```

#### 场景：软件，网站和娱乐产品点评

宋亮的范例（内容可参考，格式不对）

要准备的数据内容不变，仍然是收集 1500 个题材，其中 500 个准备相应的预置议题

准备预置议题时，思路可以拓宽。不仅仅可以对该产品/该内容进行某方面评价，也可以是引用该产品/该内容去发从其他角度切入的相关议题，例如，当引用“新浪微博”时，可以发以下的议题：
- 你在新浪微博上发微博多还是转发微博多？
- 你在新浪微博上经常发什么内容？
- 你对新浪微博上市有什么看法？
- 新浪微博和 twitter 有什么区别？
- 你觉得新浪微博哪里不方便？
- 你对新浪微博的 V6 版有什么看法？

按照这样的思去写议题，比较容易想，同时能给用户更好的示范。也便于将来去复用这部分数据。

``` yaml

# 第一条数据（只有题材，没有预置议题选项，这种数据共需要1000条）
- infocard:
    name: dribbble 
    site: https://dribbble.com
    desc: 这是一个在线艺术设计创作社区，是一个集创意、设计、艺术为一体的在线服务平台，网友可以在这里在线提交自己的设计作品，或者浏览欣赏他人的作品，并提出自己的见解。
    logo: http://img.teamkn.com/i/XpTh13yB.png@200h

# 第二条数据（有题材，并有预置议题和选项，这种数据共需要500条）
- infocard:
    name: 布卡漫画
    site: http://www.ibuka.cn/
    desc: 布卡漫画是一款免费的手机看漫画软件，舒适的手机阅览模式，海量国内外漫画，等你来体验哦！
    logo: http://img.teamkn.com/i/wouJCXfV.png@200h
    # logo 要求 200 × 200 的图片，传到 img4ye

  topic:
    desc: 布卡下架了好多漫画没法用了，你们现在用什么app看漫画？
    options:
      - 漫画控
      - 追追
      - 漫画岛
      - 腾讯动漫
      - 百度贴吧
```

**Comment by ben7th** [comment]
一般议题的数据准备
1. 避免一般疑问句（只有是或者否答案的疑问句），例如问”邻居总盗用我wifi怎么办“就比”你是否愿意和邻居共享wifi“要好
2. 预置选项不用做到都对议题完整自洽。
3. 不能特别冷门，至少要本团队的人立刻能知道（不用查资料）是什么意思

``` yaml
# 类似数据准备 500 条
- desc: 哪些垃圾食品让你欲罢不能？
  options:
    - 烧烤
    - 薯片等膨化食品
    - 汽水可乐等碳酸饮料
    - 方便面/粉
    - 辣条
    - 罐头食品
    - 冰淇淋
```
