### ISSUE TITLE
预置数据准备

### ISSUE THREAD

**Issue by ben7th** [mindpin/TouchIdea#34]
任务来源：
https://github.com/mindpin/TouchIdea/issues/30

内容参考：
http://markdown.4ye.me/oQPQPIqj
（夏实写的，格式不对，格式要按下面的来）

---

执行方案：
### 第一批数据：商品分享

每个人找 100 个就行了，应该不会找重。可以是自己买过或想买的东西。

其中的 25 的，准备相应的议题和选项，选项数需要大于等于三条

商品来源限以下十个来源：
淘宝，天猫，京东，亚马逊，当当，一号店，无印良品，国美，宜家，易迅

要求找来的数据，十个来源的都要有，但比例自己决定

格式，提交 yaml 文件，由吴笛汇总

``` yaml
# 第一条数据（只有商品网址，没有预置议题选项，这种数据每人需要 75 条）
- url: http://detail.tmall.com/item.htm?spm=a230r.1.14.28.wo35GN&id=18699534618&ns=1&abbucket=3

# 第二条数据（有商品网址，有预置议题和选项，这种数据每人需要 25 条）
- url: http://detail.tmall.com/item.htm?id=39151345462
  desc: 对于这种概念手表大家有什么看法？
  options:
    - 好看
    - 不好看
    - 智商不够看不懂
    - 太贵！求淘宝同款
```

**特别注意：由于我们会给没有预置议题的商品网址生成默认的议题和选项（选项是：好，不好，没想法）；所以，准备带有议题和选项的商品网址时，就不要从这个角度去准备议题选项了。**

---
### 第二批数据：软件网站娱乐产品题材

内容参考：http://markdown.4ye.me/uZjulSOp/8
宋亮写的，内容可以参考，格式不对，格式按下面的来

每个人找 250 个。为了避免找重，按照首字母分配。
A - D 吴笛
E - H 陈啸峰
I - L 肖少富
M - P 李飞
Q - U 宋亮
V - Z 夏实

按产品英文名或中文名的首字母（拼音首字母），随意，不要太纠结

找来的应该是属于 工具，教育，社区，休闲，游戏 类的产品。

举例：
工具：processon
教育：可汗学院
社区：微博，贴吧
休闲：美图秀秀，美拍，起点
游戏：minecraft

如果一个东西属于两个分类，则都注明

并且要对其中的 85 个准备议题和选项。

准备预置议题时，思路可以拓宽。不仅仅可以对该产品/该内容进行某方面评价，也可以是引用该产品/该内容去发从其他角度切入的相关议题，例如，当引用“新浪微博”时，可以发以下的议题：
- 你在新浪微博上发微博多还是转发微博多？
- 你在新浪微博上经常发什么内容？
- 你对新浪微博上市有什么看法？
- 新浪微博和 twitter 有什么区别？
- 你觉得新浪微博哪里不方便？
- 你对新浪微博的 V6 版有什么看法？

按照这样的思去写议题，比较容易想，同时能给用户更好的示范。也便于将来去复用这部分数据。

``` yaml

# 第一条数据（只有题材，没有预置议题选项，这种数据每人需要 165 条）
- infocard:
    name: dribbble 
    site: https://dribbble.com
    desc: 这是一个在线艺术设计创作社区，是一个集创意、设计、艺术为一体的在线服务平台，网友可以在这里在线提交自己的设计作品，或者浏览欣赏他人的作品，并提出自己的见解。
    logo: http://img.teamkn.com/i/XpTh13yB.png@200h
    # logo 要求 200 × 200 的图片，传到 img4ye
    tag: 社区

# 第二条数据（有题材，并有预置议题和选项，这种数据每人需要 85 条）
- infocard:
    name: 布卡漫画
    site: http://www.ibuka.cn/
    desc: 布卡漫画是一款免费的手机看漫画软件，舒适的手机阅览模式，海量国内外漫画，等你来体验哦！
    logo: http://img.teamkn.com/i/wouJCXfV.png@200h
    # logo 要求 200 × 200 的图片，传到 img4ye
    tag: 休闲, 社区

  topic:
    desc: 布卡下架了好多漫画没法用了，你们现在用什么app看漫画？
    options:
      - 漫画控
      - 追追
      - 漫画岛
      - 腾讯动漫
      - 百度贴吧
```

---
### 第三批数据：一般议题

内容参考：http://markdown.4ye.me/I6EK1aE1/8
宋亮写的，内容可以参考，格式不对，格式按下面的来

每个人准备 100 个。根据楼上列出的原则来准备。比较随意

几条原则
1. 避免一般疑问句（只有是或者否答案的疑问句），例如问”邻居总盗用我wifi怎么办“就比”你是否愿意和邻居共享wifi“要好
2. 预置选项不用做到都对议题完整自洽。
3. 不能特别冷门，至少要本团队的人立刻能知道（不用查资料）是什么意思
4. 不要出知识考查题，或者只有一个答案是对的这种题目。我们发的是投票议题，而不是考试题目。这是一个趣味投票系统而不是一个考试系统。

从 4 月 22 号开始，按照 第一批，第二批，第三批 数据这样准备；
每天下午五点提交一次；
由吴笛负责汇总和校验；
由陈晓峰和李飞负责数据导入；

每个人先完成自己负责的数据量。如果因为其他原因导致工作时间被占用，则先完成自己数据量的人可以帮其他人完成；

格式

``` yaml
# 类似数据每人准备 100 条
- desc: 哪些垃圾食品让你欲罢不能？
  options:
    - 烧烤
    - 薯片等膨化食品
    - 汽水可乐等碳酸饮料
    - 方便面/粉
    - 辣条
    - 罐头食品
    - 冰淇淋
```

---

如何提交，如何汇总
1. 按第一批，第二批，第三批的顺序准备。整个团队做完第一批再做第二批，做完第二批再做第三批；每个人自己做完了第一批，而别人还没做完的话，可以开始做下一批；
2. 每天下午五点提交一次 yaml 文件，给宋亮一份并给吴笛一份，写多少算多少。如果有人进度落后，则灵活调整由其他人代劳。提交 yaml 的时候注用注释明一下数量。
3. 吴笛的校对每天做一次，主要校对的因素有：数量，格式大致正确，是否有重复。
4. 如果中途有任何问题，问宋亮。
